name: 'Terraform Format Check'

on:
  push:
    branches:
    - "master"
  pull_request:

permissions:
  contents: read

jobs:
  check-format:
    name: 'Check Terraform Format'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Format Check
      run: terraform fmt -check -recursive
